version: '3.8'

services:
    nginx:
        container_name: nginx_ii
        image: nginx:alpine
        ports:
            - "6060:80"
        depends_on:
            - app
            - db
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network
    db:
        image: mysql
        container_name: mysql_ii
        ports:
            - "3309:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=risk_ranking
            - MYSQL_ROOT_PASSWORD=password
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_ii
        ports:
            - "3500:80"
        depends_on:
            - db
    app:
        build:
            context: .
        ports:
            - "9300:9000"  # PHP-FPM port
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - app-network

    mailhog:
        container_name: mailhog_ii
        image: mailhog/mailhog
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
